"""add genre field to books

Revision ID: e66344cec24d
Revises: e2615d975559
Create Date: 2025-05-28 22:48:30.426161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66344cec24d'
down_revision: Union[str, None] = 'e2615d975559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('genre', sa.String(), nullable=True))
    # op.alter_column('users', 'is_librarian',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'is_librarian',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=True)
    op.drop_column('books', 'genre')
    # ### end Alembic commands ###
